// <auto-generated />
using System;
using AtosPersonalFinance_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtosPersonalFinance_API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtosPersonalFinance_API.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salário",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rendimento de Investimentos",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Venda de Produtos",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reembolsos",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aluguéis Recebidos",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Outros",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alimentação",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Moradia (Aluguel/Financiamento)",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Transporte",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Educação",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Saúde",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Lazer e Entretenimento",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Compras",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dívidas e Empréstimos",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Investimentos",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Doações e Caridade",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Outros",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("AtosPersonalFinance_API.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("created_AT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("updated_AT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("AtosPersonalFinance_API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AtosPersonalFinance_API.Models.Entities.Transaction", b =>
                {
                    b.HasOne("AtosPersonalFinance_API.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_category");

                    b.HasOne("AtosPersonalFinance_API.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_user");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AtosPersonalFinance_API.Models.Entities.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AtosPersonalFinance_API.Models.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
